//! Port of Email::Receiver (lib/email/receiver.rb) and Email::Processor
//! for a reply by a known user to a reply key: the incoming_emails row,
//! the body (Discourse's markers cut, the reply trimmed, HTML as
//! markdown), the post through PostCreator, and the rejection email the
//! sender gets when it fails.
//!
//! Everything a reply to a reply key does not reach is refused, each with
//! its reason: staged users, bounces, attachments, forwarded emails,
//! group and category addresses (email_in), likes and notification
//! levels by email, and messages (PMs).

use std::sync::LazyLock;

use regex::Regex;
use sqlx::PgConnection;

use super::html_to_markdown;
use super::incoming::{self, Incoming};
use super::reply_trimmer;
use crate::site_settings::SiteSettings;
use crate::{AppError, AppState, Unsupported};

/// `IncomingEmail.created_via_types`
fn created_via(source: Option<&str>) -> i32 {
    match source {
        Some("handle_mail") => 1,
        Some("pop3_poll") => 2,
        Some("group_smtp") => 4,
        _ => 0,
    }
}

/// `Receiver.formats`
pub mod formats {
    pub const PLAINTEXT: i32 = 1;
    pub const MARKDOWN: i32 = 2;
}

/// A Receiver error that leaves no rejection email: the incoming email
/// keeps its class name in `error`.
#[derive(Debug)]
struct Silent(&'static str);

/// What process_internal ends with.
enum Ended {
    Done,
    /// An error Email::Processor only records.
    Silent(Silent),
    /// An error Email::Processor answers with a rejection email.
    Rejected(Rejection),
}

/// A Receiver error and what its rejection email says.
#[derive(Debug)]
struct Rejection {
    class: &'static str,
    /// The exception's message (InvalidPost carries the post's errors).
    message: String,
    args: Vec<(String, String)>,
}

impl Rejection {
    fn new(class: &'static str) -> Rejection {
        Rejection {
            class,
            message: String::new(),
            args: Vec::new(),
        }
    }

    /// `Email::Processor#handle_failure`'s template for the error.
    fn template(&self) -> &'static str {
        match self.class {
            "EmptyEmailError" | "NoBodyDetectedError" => "email_reject_empty",
            "UserNotFoundError" => "email_reject_user_not_found",
            "ScreenedEmailError" => "email_reject_screened_email",
            "EmailNotAllowed" => "email_reject_not_allowed_email",
            "EmailAliasNotAllowed" => "email_reject_email_alias",
            "AutoGeneratedEmailError" => "email_reject_auto_generated",
            "InactiveUserError" => "email_reject_inactive_user",
            "SilencedUserError" => "email_reject_silenced_user",
            "BadDestinationAddress" => "email_reject_bad_destination_address",
            "StrangersNotAllowedError" => "email_reject_strangers_not_allowed",
            "InsufficientTrustLevelError" => "email_reject_insufficient_trust_level",
            "ReplyUserNotMatchingError" => "email_reject_reply_user_not_matching",
            "TopicNotFoundError" => "email_reject_topic_not_found",
            "TopicClosedError" => "email_reject_topic_closed",
            "InvalidPost" | "UnsubscribeNotAllowed" => {
                if self.message.chars().count() > 6 {
                    "email_reject_invalid_post_specified"
                } else {
                    "email_reject_invalid_post"
                }
            }
            "TooShortPost" => "email_reject_post_too_short",
            "InvalidPostAction" => "email_reject_invalid_post_action",
            "OldDestinationError" => "email_reject_old_destination",
            "ReplyNotAllowedError" => "email_reject_reply_not_allowed",
            "ReplyToDigestError" => "email_reject_reply_to_digest",
            "TooManyRecipientsError" => "email_reject_too_many_recipients",
            _ => "email_reject_unrecognized_error",
        }
    }
}

/// NewPostManager's errors as the Receiver raises them: TooShortPost when
/// the raw is too short, else InvalidPost with the errors.
fn invalid_post(
    state: &AppState,
    s: &SiteSettings,
    errors: &[String],
) -> Result<Rejection, AppError> {
    let attribute = state
        .i18n
        .t("activerecord.attributes.post.raw")
        .unwrap_or("")
        .trim()
        .to_string();
    let min = s.get("min_post_length")?.to_i();
    let form = if min == 1 { "one" } else { "other" };
    let too_short = state
        .i18n
        .t_with(
            &format!("errors.messages.too_short.{form}"),
            &[("count", &min.to_string())],
        )
        .unwrap_or_default();
    let too_short = too_short.trim();
    if errors
        .iter()
        .any(|e| e.contains(attribute.as_str()) && e.contains(too_short))
    {
        let mut r = Rejection::new("TooShortPost");
        r.args.push(("count".into(), min.to_string()));
        return Ok(r);
    }
    let mut r = Rejection::new("InvalidPost");
    r.message = errors.join("\n");
    Ok(r)
}

/// Ruby's `Array#inspect` for a list of strings.
fn inspect(list: &[String]) -> String {
    let items: Vec<String> = list
        .iter()
        .map(|s| format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")))
        .collect();
    format!("[{}]", items.join(", "))
}

/// `Email::Processor#handle_failure` for a rejection, then
/// `set_incoming_email_rejection_message`: the email to the sender (one a
/// day per address and kind), and its text kept on the incoming email.
async fn reject(
    state: &AppState,
    conn: &mut PgConnection,
    s: &SiteSettings,
    mail: &Incoming,
    rejection: Rejection,
    incoming_id: Option<i32>,
) -> Result<(), AppError> {
    let template = rejection.template();
    if template == "email_reject_unrecognized_error" {
        return Err(Unsupported("rejections for unrecognized errors").into());
    }
    let mut args: Vec<(String, String)> = rejection.args;
    if template == "email_reject_invalid_post_specified" {
        args.push(("post_error".into(), rejection.message.clone()));
    }
    args.push((
        "former_title".into(),
        mail.subject.clone().unwrap_or_default(),
    ));
    args.push(("destination".into(), inspect(&mail.to)));
    let host = crate::pretty_text::Host::from_state(state);
    let ctx = super::sender::Ctx {
        host: &host,
        settings: s,
        config: &state.config,
        i18n: &state.i18n,
        mailer: &state.mailer,
    };
    let refs: Vec<(&str, &str)> = args.iter().map(|(k, v)| (k.as_str(), v.as_str())).collect();
    let built = super::account::build_template(
        &mut *conn,
        &ctx,
        &format!("system_messages.{template}"),
        &mail.from_addresses.join(", "),
        &refs,
        None,
    )
    .await?;
    let text = built.message.text.clone();
    // can_send_rejection_email?: Redis's rejection_email:<from>:<type>:<date>.
    let today: chrono::NaiveDate = sqlx::query_scalar("SELECT now()::date")
        .fetch_one(&mut *conn)
        .await?;
    let key = format!(
        "rejection_email:{}:{template}:{today}",
        inspect(&mail.from_addresses)
    );
    if crate::owned_schema::set_once(&mut *conn, &key, 25 * 3600).await? {
        super::sender::send(&mut *conn, &ctx, built, template, None).await?;
    }
    if let Some(id) = incoming_id {
        let current: String = sqlx::query_scalar("SELECT raw FROM incoming_emails WHERE id = $1")
            .bind(id)
            .fetch_one(&mut *conn)
            .await?;
        let limit = s.get("raw_rejected_email_max_length")?.to_i().max(0) as usize;
        let raw = incoming::clean(&incoming::parse(&current)?, limit)?;
        sqlx::query(
            "UPDATE incoming_emails SET rejection_message = $2, raw = $3, updated_at = clock_timestamp() WHERE id = $1",
        )
        .bind(id)
        .bind(&text)
        .bind(&raw)
        .execute(&mut *conn)
        .await?;
    }
    Ok(())
}

/// `previous_replies_regex` and `reply_above_line_regex`, from every
/// locale's translation (vendor/discourse/config/email_markers.tsv).
static MARKERS: LazyLock<(Regex, Regex)> = LazyLock::new(|| {
    let source = include_str!("../../vendor/discourse/config/email_markers.tsv");
    let strings = |key: &str| {
        let mut out: Vec<String> = Vec::new();
        for line in source.lines() {
            if let Some((k, v)) = line.split_once('\t') {
                let v = v.replace("\\\"", "\"").replace("\\\\", "\\");
                if k == key && !out.contains(&v) {
                    out.push(v);
                }
            }
        }
        out.iter()
            .map(|s| regex::escape(s))
            .collect::<Vec<_>>()
            .join("|")
    };
    (
        Regex::new(&format!(
            r"(?is)\A--[- ]\n\*(?:{})\*\n",
            strings("previous_discussion")
        ))
        .expect("the previous replies markers"),
        Regex::new(&format!(r"(?is)\n(?:{})\n", strings("reply_above_line")))
            .expect("the reply above line markers"),
    )
});

/// `reply.split(regex)[0]`: Ruby's split drops trailing empty pieces, so
/// a text that is all marker has no first piece.
fn split_first(text: &str, re: &Regex) -> Option<String> {
    let mut pieces: Vec<&str> = re.split(text).collect();
    while pieces.last().is_some_and(|p| p.is_empty()) {
        pieces.pop();
    }
    pieces.first().map(|p| p.to_string())
}

/// `trim_discourse_markers`
fn trim_discourse_markers(reply: &str) -> Result<String, Unsupported> {
    if crate::ruby::is_blank(reply) {
        return Ok(String::new());
    }
    let (previous, above) = &*MARKERS;
    let reply = split_first(reply, previous).ok_or(Unsupported(
        "an email that is only Discourse's previous replies",
    ))?;
    split_first(&reply, above).ok_or(Unsupported("an email that is only the reply-above line"))
}

fn blank(s: &Option<String>) -> bool {
    s.as_deref().is_none_or(crate::ruby::is_blank)
}

/// `select_body`: the reply text, what was elided, and its format; None
/// when the email has neither a text nor an HTML body.
pub fn select_body(
    mail: &Incoming,
    s: &SiteSettings,
    base_url: &str,
) -> Result<Option<(String, String, i32)>, AppError> {
    let mut text = Incoming::fix_charset(mail.text_part())?;
    let html = Incoming::fix_charset(mail.html_part())?;
    if blank(&text) && blank(&html) {
        return Ok(None);
    }
    let mut elided: Option<String> = None;
    if !blank(&text) {
        let trimmed = trim_discourse_markers(text.as_deref().unwrap_or(""))?;
        (text, elided) = trim_reply(&trimmed, s)?;
    }
    // The HTML as markdown: a known client's quote and signature cut by
    // its marks, or the whole of it trimmed like text.
    let (markdown, elided_markdown) = match html.as_deref().filter(|h| !crate::ruby::is_blank(h)) {
        Some(h) => {
            let opts = html_to_markdown::Options {
                keep_img_tags: true,
                keep_cid_imgs: true,
            };
            let schemes = s.get("allowed_href_schemes")?.to_s();
            match html_to_markdown::extract(h, &opts, &schemes)? {
                Some((markdown, elided)) => (markdown, Some(elided)),
                None => {
                    let markdown = html_to_markdown::to_markdown(h, &opts, &schemes);
                    trim_reply(&trim_discourse_markers(&markdown)?, s)?
                }
            }
        }
        None => (None, None),
    };
    let mut format = formats::PLAINTEXT;
    if blank(&text) || (s.get("incoming_email_prefer_html")?.truthy() && !blank(&markdown)) {
        text = markdown;
        elided = elided_markdown;
        format = formats::MARKDOWN;
    }
    if s.get("strip_incoming_email_lines")?.truthy() && !blank(&text) {
        text = Some(strip_lines(text.as_deref().unwrap_or("")));
    }
    let unsubscribe = Regex::new(&format!("{base_url}/email/unsubscribe/[0-9a-fA-F]{{64}}"))
        .map_err(|_| Unsupported("a base URL that is not a valid regex"))?;
    let strip = |t: Option<String>| {
        unsubscribe
            .replace_all(t.as_deref().unwrap_or(""), "")
            .into_owned()
    };
    Ok(Some((strip(text), strip(elided), format)))
}

/// `trim_reply_and_extract_elided`: the reply and what was cut, or the
/// text as is when trimming is off.
fn trim_reply(text: &str, s: &SiteSettings) -> Result<(Option<String>, Option<String>), AppError> {
    if !s.get("trim_incoming_emails")?.truthy() {
        return Ok((Some(text.to_string()), Some(String::new())));
    }
    Ok(match reply_trimmer::trim(text) {
        Some((t, e)) => (Some(t), Some(e)),
        None => (None, None),
    })
}

/// `strip_incoming_email_lines`: each line stripped, list items and code
/// blocks left alone.
fn strip_lines(text: &str) -> String {
    let mut in_code: Option<&str> = None;
    let mut out = String::new();
    for line in text.split_inclusive('\n') {
        let mut stripped = reply_trimmer::ruby_strip(line).to_string();
        stripped.push('\n');
        let b = stripped.as_bytes();
        if (b[0] == b'*' || b[0] == b'-' || b[0] == b'+') && b.get(1) == Some(&b' ') {
            out.push_str(line);
            continue;
        }
        if in_code.is_none() && stripped.starts_with("```") {
            in_code = Some("```");
        } else if in_code == Some("```") && stripped.starts_with("```") {
            in_code = None;
        } else if in_code.is_none() && stripped.starts_with("[code") {
            in_code = Some("[code]");
        } else if in_code == Some("[code]") && stripped.starts_with("[/code]") {
            in_code = None;
        }
        if in_code.is_some() {
            out.push_str(line);
        } else {
            out.push_str(&stripped);
        }
    }
    out
}

/// `subject`: the mail's subject without NULs, at most 255 characters,
/// or the default one.
pub fn subject(mail: &Incoming, from_email: Option<&str>, i18n: &crate::i18n::I18n) -> String {
    match &mail.subject {
        Some(s) => s.replace('\0', "").chars().take(255).collect(),
        None => i18n
            .t_with(
                "emails.incoming.default_subject",
                &[("email", from_email.unwrap_or(""))],
            )
            .unwrap_or_default(),
    }
}

static AUTO_SUBJECT: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)\A\s*(Auto:|Automatic reply|Autosvar|Automatisk svar|Automatisch antwoord|Abwesenheitsnotiz|Risposta Non al computer|Automatisch antwoord|Auto Response|Respuesta automática|Fuori sede|Out of Office|Frånvaro|Réponse automatique)",
    )
    .unwrap()
});
static AUTO_FROM: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(mailer[\-_]?daemon|post[\-_]?master|no[\-_]?reply)@").unwrap()
});
static AUTO_HEADERS: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)auto[\-_]?(response|submitted|replied|reply|generated|respond)|holidayreply|machinegenerated",
    )
    .unwrap()
});

/// `is_auto_generated?`
pub fn is_auto_generated(
    mail: &Incoming,
    s: &SiteSettings,
    from_email: Option<&str>,
) -> Result<bool, AppError> {
    let allowlist = s.get("auto_generated_allowlist")?.to_s();
    if let Some(from) = from_email
        && allowlist.split('|').any(|a| a == from)
    {
        return Ok(false);
    }
    let precedence = mail.root.field("Precedence").unwrap_or("");
    if Regex::new(r"(?i)list|junk|bulk|auto_reply")
        .unwrap()
        .is_match(precedence)
    {
        return Ok(true);
    }
    if AUTO_FROM.is_match(mail.root.field("From").unwrap_or("")) {
        return Ok(true);
    }
    if mail
        .subject
        .as_deref()
        .is_some_and(|s| AUTO_SUBJECT.is_match(s))
    {
        return Ok(true);
    }
    Ok(AUTO_HEADERS.is_match(&mail.header_text("X-Auto-Response-Suppress")))
}

/// `reply_by_email_address_regex(extract_reply_key, include_verp)`
fn reply_address_regex(s: &SiteSettings, include_verp: bool) -> Result<Option<Regex>, AppError> {
    let main = s.get("reply_by_email_address")?.to_s();
    let mut addresses: Vec<String> = vec![main.clone()];
    addresses.extend(
        s.get("alternative_reply_by_email_addresses")?
            .to_s()
            .split('|')
            .map(str::to_string),
    );
    if include_verp && !main.is_empty() && main.contains('+') {
        addresses.push(main.replacen("%{reply_key}", "verp-%{reply_key}", 1));
    }
    let parts: Vec<String> = addresses
        .iter()
        .filter(|a| !a.is_empty())
        .map(|a| {
            regex::escape(a)
                .replace(r"\+", r"\+?")
                .replace(r"%\{reply_key\}", "([0-9a-fA-F]{32})?")
        })
        .collect();
    if parts.is_empty() {
        return Ok(None);
    }
    Ok(Some(Regex::new(&parts.join("|")).map_err(|_| {
        Unsupported("a reply_by_email_address that is not a valid regex")
    })?))
}

/// The Rails class name an error is recorded under.
fn error_class(name: &str) -> String {
    format!("Email::Receiver::{name}")
}

/// `Email::Processor.process!(mail, source:)`
pub async fn process(state: &AppState, raw: &str, source: Option<&str>) -> Result<(), AppError> {
    if raw.trim().is_empty() {
        return Err(Unsupported("rejection emails (EmptyEmailError)").into());
    }
    let mail = incoming::parse(raw)?;
    let mut conn = state.pool.acquire().await?;
    let s = SiteSettings::load(&mut conn, &state.site_setting_defs, &state.config.globals).await?;

    // is_blocked?
    let subject_raw = mail.subject.clone().unwrap_or_default();
    let titles = s.get("ignore_by_title")?.to_s();
    if !titles.is_empty() {
        let escaped: Vec<String> = titles.split('|').map(regex::escape).collect();
        if Regex::new(&format!("(?i){}", escaped.join("|"))).is_ok_and(|r| r.is_match(&subject_raw))
        {
            return Ok(());
        }
    }
    if s.get("ignore_by_title_regex")?.presence().is_some() {
        return Err(Unsupported("ignore_by_title_regex (a Ruby regex)").into());
    }
    let existing: bool =
        sqlx::query_scalar("SELECT EXISTS (SELECT 1 FROM incoming_emails WHERE message_id = $1)")
            .bind(&mail.message_id)
            .fetch_one(&mut *conn)
            .await?;
    if existing {
        return Ok(());
    }
    // Email::Validator.ensure_valid!
    let Some(date) = mail.date else {
        // InvalidPost, raised before there is an incoming email.
        let mut r = Rejection::new("InvalidPost");
        r.message = state
            .i18n
            .t("system_messages.email_reject_invalid_post_specified.date_invalid")
            .unwrap_or("")
            .to_string();
        return reject(state, &mut conn, &s, &mail, r, None).await;
    };

    // parse_from_field: bounces and forwarded emails are refused.
    let bounce_key = Regex::new(r"\+verp-[0-9a-fA-F]{32}@").unwrap();
    if mail.root.mime_type() == "multipart/report"
        || mail
            .all_destinations()
            .iter()
            .any(|d| bounce_key.is_match(d))
    {
        return Err(Unsupported("bounced emails").into());
    }
    let forwarded = Regex::new(r"(?i)\A[\t\p{Zs}]*(fwd?|tr)[\t\p{Zs}]?:").unwrap();
    if forwarded.is_match(&subject_raw) {
        return Err(Unsupported("forwarded emails").into());
    }
    let (from_email, _from_name) = match &mail.from {
        Some((a, n)) => (Some(a.clone()), Some(n.clone())),
        None => (None, None),
    };
    let from_user: Option<(i32, bool, bool, bool)> = match &from_email {
        Some(email) => sqlx::query_as(
            "SELECT u.id, u.active, u.staged, COALESCE(u.silenced_till > now(), FALSE) FROM users u \
             WHERE u.id = (SELECT user_id FROM user_emails WHERE lower(email) = lower($1) LIMIT 1)",
        )
        .bind(email)
        .fetch_optional(&mut *conn)
        .await?,
        None => None,
    };

    // create_incoming_email
    let limit = s.get("raw_email_max_length")?.to_i().max(0) as usize;
    let cleaned = incoming::clean(&mail, limit)?;
    let join = |list: &[String]| {
        list.iter()
            .map(|a| a.to_lowercase())
            .collect::<Vec<_>>()
            .join(";")
    };
    let incoming_id: i32 = sqlx::query_scalar(
        "INSERT INTO incoming_emails (message_id, raw, subject, from_address, to_addresses, cc_addresses, \
                                      created_via, created_at, updated_at) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, clock_timestamp(), clock_timestamp()) RETURNING id",
    )
    .bind(&mail.message_id)
    .bind(&cleaned)
    .bind(subject(&mail, from_email.as_deref(), &state.i18n))
    .bind(&from_email)
    .bind(join(&mail.to))
    .bind(join(&mail.cc))
    .bind(created_via(source))
    .fetch_one(&mut *conn)
    .await?;

    let ended = process_internal(
        state,
        &mut conn,
        &s,
        &mail,
        raw,
        date,
        incoming_id,
        from_email.as_deref(),
        from_user,
    )
    .await;
    match ended {
        Ok(Ended::Done) => Ok(()),
        Ok(Ended::Silent(Silent(name))) => {
            sqlx::query("UPDATE incoming_emails SET error = $2 WHERE id = $1")
                .bind(incoming_id)
                .bind(error_class(name))
                .execute(&mut *conn)
                .await?;
            Ok(())
        }
        Ok(Ended::Rejected(rejection)) => {
            sqlx::query("UPDATE incoming_emails SET error = $2 WHERE id = $1")
                .bind(incoming_id)
                .bind(error_class(rejection.class))
                .execute(&mut *conn)
                .await?;
            reject(state, &mut conn, &s, &mail, rejection, Some(incoming_id)).await
        }
        Err(e) => Err(e),
    }
}

#[allow(clippy::too_many_arguments)]
async fn process_internal(
    state: &AppState,
    conn: &mut PgConnection,
    s: &SiteSettings,
    mail: &Incoming,
    raw: &str,
    date: chrono::NaiveDateTime,
    incoming_id: i32,
    from_email: Option<&str>,
    from_user: Option<(i32, bool, bool, bool)>,
) -> Result<Ended, AppError> {
    let Some(from_email) = from_email.filter(|f| !f.is_empty()) else {
        return Ok(Ended::Silent(Silent("NoSenderDetectedError")));
    };
    if reply_address_regex(s, false)?.is_some_and(|r| r.is_match(from_email)) {
        return Ok(Ended::Silent(Silent("FromReplyByAddressError")));
    }
    let screened: bool = sqlx::query_scalar("SELECT EXISTS (SELECT 1 FROM screened_emails)")
        .fetch_one(&mut *conn)
        .await?;
    if screened {
        return Err(Unsupported("screened emails (ScreenedEmail.should_block?)").into());
    }
    let Some((user_id, active, staged, silenced)) = from_user else {
        return Err(Unsupported("emails from unknown senders (staged users)").into());
    };
    // log_and_validate_user
    sqlx::query("UPDATE incoming_emails SET user_id = $2 WHERE id = $1")
        .bind(incoming_id)
        .bind(user_id)
        .execute(&mut *conn)
        .await?;
    if staged {
        return Err(Unsupported("emails from staged users").into());
    }
    if !active {
        return Ok(Ended::Rejected(Rejection::new("InactiveUserError")));
    }
    if silenced {
        return Ok(Ended::Rejected(Rejection::new("SilencedUserError")));
    }
    let mut recipients: Vec<String> = Vec::new();
    for a in mail.to.iter().chain(&mail.cc).chain(&mail.bcc) {
        let a = a.to_lowercase();
        if !recipients.contains(&a) {
            recipients.push(a);
        }
    }
    if recipients.len() as i64 > s.get("maximum_recipients_per_new_group_email")?.to_i() {
        let mut r = Rejection::new("TooManyRecipientsError");
        r.args
            .push(("recipients_count".into(), recipients.len().to_string()));
        r.args.push((
            "max_recipients_count".into(),
            s.get("maximum_recipients_per_new_group_email")?
                .to_i()
                .to_string(),
        ));
        return Ok(Ended::Rejected(r));
    }

    let urls = crate::url::Urls {
        config: &state.config,
        settings: s,
    };
    let base_url = urls.base_url()?;
    let (body, elided, _format) = select_body(mail, s, &base_url)?.unwrap_or_default();
    if mail.attachment_count() > 0 {
        return Err(Unsupported("email attachments").into());
    }
    if crate::ruby::is_blank(&body) {
        return Ok(Ended::Rejected(Rejection::new("NoBodyDetectedError")));
    }
    if is_auto_generated(mail, s, Some(from_email))? {
        sqlx::query("UPDATE incoming_emails SET is_auto_generated = TRUE WHERE id = $1")
            .bind(incoming_id)
            .execute(&mut *conn)
            .await?;
        if s.get("block_auto_generated_emails")?.truthy() {
            return Ok(Ended::Rejected(Rejection::new("AutoGeneratedEmailError")));
        }
    }
    // subscription_action_for
    if s.get("unsubscribe_via_email")?.truthy() {
        let said = |t: &str| t.to_lowercase() == "unsubscribe";
        if said(&subject(mail, Some(from_email), &state.i18n)) || said(&body) {
            return Err(Unsupported("unsubscribing by email").into());
        }
    }
    if s.get("email_in")?.truthy() {
        return Err(Unsupported("group and category addresses (email_in)").into());
    }
    if !s.get("find_related_post_with_key")?.truthy() {
        return Err(Unsupported("finding the related post without a key").into());
    }
    // find_related_post(force: true): a reply to a post in a category
    // needs reply by email on.
    if let Some(post_id) = related_post(conn, state, s, mail).await? {
        let in_category: bool = sqlx::query_scalar(
            "SELECT EXISTS (SELECT 1 FROM posts p JOIN topics t ON t.id = p.topic_id \
             WHERE p.id = $1 AND t.category_id IS NOT NULL)",
        )
        .bind(post_id)
        .fetch_one(&mut *conn)
        .await?;
        if in_category && !s.get("reply_by_email_enabled")?.truthy() {
            return Ok(Ended::Rejected(Rejection::new("ReplyNotAllowedError")));
        }
    }

    // destinations: the reply keys the addresses carry.
    let Some(reply_re) = reply_address_regex(s, false)? else {
        return Ok(Ended::Rejected(Rejection::new("BadDestinationAddress")));
    };
    let mut destination: Option<(i32, i32)> = None;
    for address in mail.all_destinations() {
        let Some(c) = reply_re.captures(&address) else {
            continue;
        };
        for key in c.iter().skip(1).flatten() {
            let found: Option<(i32, i32)> = sqlx::query_as(
                "SELECT post_id, user_id FROM post_reply_keys WHERE reply_key = $1::uuid",
            )
            .bind(key.as_str())
            .fetch_optional(&mut *conn)
            .await?;
            if found.is_some() {
                destination = found;
                break;
            }
        }
        if destination.is_some() {
            break;
        }
    }
    let Some((post_id, key_user_id)) = destination else {
        return Ok(Ended::Rejected(Rejection::new("BadDestinationAddress")));
    };
    if key_user_id != user_id {
        return Err(Unsupported("replies to someone else's reply key (forwarded keys)").into());
    }

    // create_reply
    #[derive(sqlx::FromRow)]
    struct Target {
        topic_id: i32,
        post_number: i32,
        post_deleted: bool,
        topic_deleted: Option<bool>,
        archetype: Option<String>,
        closed: Option<bool>,
    }
    let target: Option<Target> = sqlx::query_as(
        "SELECT p.topic_id, p.post_number, p.deleted_at IS NOT NULL AS post_deleted, \
                t.deleted_at IS NOT NULL AS topic_deleted, t.archetype, t.closed \
         FROM posts p LEFT JOIN topics t ON t.id = p.topic_id WHERE p.id = $1",
    )
    .bind(post_id)
    .fetch_optional(&mut *conn)
    .await?;
    let Some(target) = target else {
        return Err(Unsupported("reply keys for posts that are gone").into());
    };
    if target.topic_deleted.is_none_or(|d| d) {
        return Ok(Ended::Rejected(Rejection::new("TopicNotFoundError")));
    }
    if target.archetype.as_deref() == Some("private_message") {
        return Err(Unsupported("replies to messages by email").into());
    }
    let trimmed_body = reply_trimmer::ruby_strip(&body).to_lowercase();
    let like_title = state
        .i18n
        .t("post_action_types.like.title")
        .unwrap_or("Like")
        .to_lowercase();
    if ["+1", "<3", "❤", like_title.as_str()].contains(&trimmed_body.as_str()) {
        return Err(Unsupported("likes by email").into());
    }
    if body.len() <= 40 && ["mute", "track", "watch"].contains(&trimmed_body.as_str()) {
        return Err(Unsupported("notification levels by email").into());
    }
    if target.closed == Some(true) {
        return Ok(Ended::Rejected(Rejection::new("TopicClosedError")));
    }
    let mut raw_post = body.clone();
    if !crate::ruby::is_blank(&elided) && s.get("always_show_trimmed_content")?.truthy() {
        raw_post.push_str(&elided_html(&elided, &state.i18n));
    }

    // create_post
    if s.get("email_in_spam_header")?.to_s() != "none" {
        return Err(Unsupported("spam headers on incoming email").into());
    }
    if mail.root.field("Authentication-Results").is_some() {
        return Err(Unsupported("Authentication-Results on incoming email").into());
    }
    let now: chrono::NaiveDateTime = sqlx::query_scalar("SELECT clock_timestamp()::timestamp")
        .fetch_one(&mut *conn)
        .await?;
    let created_at = date.min(now);
    let session_user = crate::session::current::SessionUser::load(&mut *conn, user_id)
        .await?
        .ok_or(Unsupported("a user that vanished"))?;
    let guardian = crate::guardian::Guardian::for_user(&mut *conn, &session_user).await?;
    let host = crate::pretty_text::Host::from_state(state);
    let ctx = crate::posting::Ctx {
        host: &host,
        settings: s,
        config: &state.config,
        i18n: &state.i18n,
    };
    let outcome = crate::posting::create::create(
        &state.pool,
        &ctx,
        &guardian,
        crate::posting::create::NewPost {
            raw: raw_post,
            topic_id: Some(target.topic_id),
            reply_to_post_number: (!target.post_deleted).then_some(target.post_number),
            email: Some(crate::posting::create::EmailOrigin {
                raw_email: raw.to_string(),
                created_at,
                incoming_email_id: incoming_id,
                message_id: mail.message_id.clone(),
            }),
            ..Default::default()
        },
    )
    .await?;
    match outcome {
        crate::posting::create::Outcome::Created { .. } => Ok(Ended::Done),
        crate::posting::create::Outcome::Invalid(errors) => {
            Ok(Ended::Rejected(invalid_post(state, s, &errors)?))
        }
        // The guardian's can_create_post?(topic), checked first in Rails.
        crate::posting::create::Outcome::Forbidden => {
            Ok(Ended::Rejected(Rejection::new("ReplyNotAllowedError")))
        }
        crate::posting::create::Outcome::InvalidParameter(_) => {
            Err(Unsupported("posts by email with invalid parameters").into())
        }
    }
}

/// `find_related_post(force: true)`: the latest post the In-Reply-To and
/// References ids name.
async fn related_post(
    conn: &mut PgConnection,
    state: &AppState,
    s: &SiteSettings,
    mail: &Incoming,
) -> Result<Option<i32>, AppError> {
    let mut ids: Vec<String> = Vec::new();
    for id in mail.in_reply_to.iter().chain(&mail.references) {
        if !id.is_empty() && !ids.contains(id) {
            ids.push(id.clone());
        }
    }
    ids.truncate(5);
    if ids.is_empty() {
        return Ok(None);
    }
    let urls = crate::url::Urls {
        config: &state.config,
        settings: s,
    };
    let host = urls.current_hostname()?;
    let generated = Regex::new(&format!(r"discourse/post/(\d+)@{}", regex::escape(&host)))
        .map_err(|_| Unsupported("a hostname that is not a valid regex"))?;
    let mut post_ids: Vec<i32> = ids
        .iter()
        .filter_map(|id| generated.captures(id).and_then(|c| c[1].parse().ok()))
        .collect();
    let found: Vec<Option<i32>> = sqlx::query_scalar(
        "SELECT id FROM posts WHERE outbound_message_id = ANY($1) \
         UNION ALL SELECT post_id FROM email_logs WHERE message_id = ANY($1) \
         UNION ALL SELECT post_id FROM incoming_emails WHERE message_id = ANY($1)",
    )
    .bind(&ids)
    .fetch_all(&mut *conn)
    .await?;
    post_ids.extend(found.into_iter().flatten());
    if post_ids.is_empty() {
        return Ok(None);
    }
    Ok(sqlx::query_scalar(
        "SELECT id FROM posts WHERE id = ANY($1) ORDER BY created_at DESC LIMIT 1",
    )
    .bind(&post_ids)
    .fetch_optional(&mut *conn)
    .await?)
}

/// `Email::Receiver.elided_html(elided)`
fn elided_html(elided: &str, i18n: &crate::i18n::I18n) -> String {
    format!(
        "\n\n<details class='elided'>\n<summary title='{}'>&#183;&#183;&#183;</summary>\n\n{elided}\n\n</details>\n",
        i18n.t("emails.incoming.show_trimmed_content").unwrap_or("")
    )
}
