-- Generated by scripts/vendor-discourse from db/fixtures/010_uploads.rb
-- at Discourse 4012b68fc58260fbdfbba5281641c6bfa332521e. Do not edit.
INSERT INTO uploads (id, user_id, original_filename, url, filesize, extension, sha1, created_at, updated_at) VALUES
  (-1, -1, 'd-logo-sketch.png', '/images/d-logo-sketch.png', 14461, 'png', '_aa4aed9d6276bab017d3991051fbb9177783abe', now(), now()),
  (-2, -1, 'd-logo-sketch-small.png', '/images/d-logo-sketch-small.png', 6175, 'png', '_bc7909b0ece56689d3551a51911e6ee1810ad31', now(), now()),
  (-3, -1, 'default-favicon.ico', '/images/default-favicon.ico', 6518, 'ico', '_bacea4851373b7c6c0ed37c8576245cc8eeef34', now(), now()),
  (-4, -1, 'default-apple-touch-icon.png', '/images/default-apple-touch-icon.png', 8166, 'png', '_9cbb8e9d5ecd0c8ec8f48ded2f11025970ab194', now(), now()),
  (-5, -1, 'discourse-logo-sketch.png', '/images/discourse-logo-sketch.png', 169105, 'png', '_abaabe41348866838adb7a011cdd530175a53df', now(), now()),
  (-6, -1, 'discourse-logo-sketch-small.png', '/images/discourse-logo-sketch-small.png', 62655, 'png', '_129430568242d1b7f853bb13ebea28b3f6af4e7', now(), now());
